export const host = "https://mgpp.pythonanywhere.com/";

export const category = [
  { link: "/", name: "All Musics", label: "All Musics", color: "bg-white/5" },
  {
    link: "/category/1970",
    name: "1970",
    label: "1970",
    color: "bg-green-500/90",
    from: "from-green-500",
    to: "to-green-900/5",
    re: "from-green-900/5",
  },
  {
    link: "/category/1980",
    name: "1980",
    label: "1980",
    color: "bg-red-500/90",
    from: "from-red-500",
    to: "to-red-900/5",
    re: "from-red-900/5",
  },
  {
    link: "/category/galau",
    name: "Galau",
    label: "Lagu Galau",
    color: "bg-cyan-500",
    from: "from-cyan-500",
    to: "to-cyan-900/5",
    re: "from-cyan-900/5",
  },
  {
    link: "/category/senang",
    name: "senang",
    label: "Lagu Senang",
    color: "bg-yellow-500",
    from: "from-yellow-500",
    to: "to-yellow-900/5",
    re: "from-yellow-900/5",
  },
  {
    link: "/category/romantis",
    name: "romantis",
    label: "Lagu Romantis",
    color: "bg-pink-500",
    from: "from-pink-500",
    to: "to-pink-900/5",
    re: "from-pink-900/5",
  },
];
